### ISSUE TITLE
Permission denied when a path to folder is provided to ImportJobRequest

### ISSUE THREAD

**Issue by konradkudziagranta** [ansys/grantami-jobqueue#158] opened 2024-11-14 15:20 UTC
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

Providing path in form of [“.“],  [“.\\”], [".\\MyFolderName"] to any ‘files’ (data_files, combined_files, attachment_files) parameter in import request, results in error:

```
Traceback (most recent call last):
  File "C:\Automation\STK\STKTests\jobqueue\jobqueue-smoke-test.py", line 240, in <module>
    import_job = api_client.create_job_and_wait(job_request=import_request)
  File "C:\Program Files\Python313\Lib\site-packages\ansys\grantami\jobqueue\_connection.py", line 354, in create_job_and_wait
    job = self.create_job(job_request=job_request)
  File "C:\Program Files\Python313\Lib\site-packages\ansys\grantami\jobqueue\_connection.py", line 396, in create_job
    job_request._post_files(api_client=self.job_queue_api)
  File "C:\Program Files\Python313\Lib\site-packages\ansys\grantami\jobqueue\_models.py", line 450, in _post_files
    file_id = api_client.upload_file(file=file.path)
  File "C:\Program Files\Python313\Lib\site-packages\ansys\grantami\serverapi_openapi\api\job_queue_api.py", line 1056, in upload_file
    data = self._upload_file_with_http_info(file, _return_http_data_only=True)
  File "C:\Program Files\Python313\Lib\site-packages\ansys\grantami\serverapi_openapi\api\job_queue_api.py", line 1097, in _upload_file_with_http_info
    return self.api_client.call_api(
  File "C:\Program Files\Python313\Lib\site-packages\ansys\openapi\common\_api_client.py", line 475, in call_api
    return self.__call_api(
  File "C:\Program Files\Python313\Lib\site-packages\ansys\openapi\common\_api_client.py", line 182, in __call_api
    post_param_tuples = self.prepare_post_parameters(post_params, files)
  File "C:\Program Files\Python313\Lib\site-packages\ansys\openapi\common\_api_client.py", line 684, in prepare_post_parameters
    with open(file_name, "rb") as f:
PermissionError: [Errno 13] Permission denied: '.'`
```

### 📝 Steps to reproduce

prepare ExcelImportJobRequest where one of files parameter is a path to a folder, and create a job with it

```python
import_request = jobqueue.ExcelImportJobRequest(
    name = "name",
    description = "description",
    template_file = ".\myTemplate.xls",
    data_files = [".\\FolderWithDataFiles"]
)

import_job = api_client.create_job_and_wait(job_request=import_request)
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

ansys-grantami-jobqueue 1.1.0rc0
ansys-grantami-serverapi-openapi 4.0.0
ansys-openapi-common 2.2.0
GRANTA_MIScriptingToolkit 4.1.75

Granta MI b. 25.1.1888

### 🐍 Which Python version are you using?

3.13

### 📦 Installed packages

```shell
ansys-grantami-jobqueue==1.1.0rc0
ansys-grantami-recordlists==1.3.0rc0
ansys-grantami-serverapi-openapi==4.0.0
ansys-openapi-common==2.2.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cryptography==43.0.3
filetype==1.2.0
GRANTA_MIScriptingToolkit @ file:///C:/Automation/STK/scripting-toolkit-4-1-75/pip/granta_miscriptingtoolkit-4.1.75-cp38-abi3-win_amd64.whl#sha256=7be8c6e46f63c29c0fde2a30911b2c3a607c5fb6443258b56e77339ca4db58b0
idna==3.10
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.1.0
keyring==25.5.0
more-itertools==10.5.0
packaging==24.2
pycparser==2.22
pyparsing==3.2.0
pypiwin32==223
pyspnego==0.11.2
python-dateutil==2.9.0.post0
pywin32==308
pywin32-ctypes==0.2.3
requests==2.32.3
requests-negotiate-sspi==0.5.2
requests_ntlm==1.3.0
six==1.16.0
sspilib==0.2.0
urllib3==2.2.3
```

**Comment by Andy-Grigg** [comment] 2024-11-14 18:59
There are a few issues here:

* `".\myTemplate.xls"` has a backslash, which is an escape character in Python. `".\myTemplate.xls"` will be converted into `".myTemplate.xls"` (because there's no such `\m` escape sequence, and it will emit a warning), and will then fail to resolve the file that doesn't exist.
* `[".\\FolderWithDataFiles"]`: Double backslash will work, but we don't support references to folders, only files.

I can't reproduce any of these issues with forward slashes, properly escaped backslash characters or `r"raw\strings"`, so I'm closing this ticket.

**Closed by Andy-Grigg** 2024-11-14 18:59 UTC
Labels: bug
